# -*- coding: utf-8 -*-
"""LLM_proj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUzxXMKr1ZjliQuCjddWVwEEJwKU9Bbo
"""

pip install -U google-genai

import os
os.environ["GEMINI_API_KEY"] = "AIzaSyD6tkn-70GI1oaOe7t11Rxv7MphI5hAvVU"

from google import genai
import os

client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

SYSTEM_PROMPT = """
You are an AI tutor for freshers.
Explain concepts step-by-step.
Use simple language.
Give real-world examples.
If needed, give a short code example.
Ask one follow-up question.
"""

# Store chat as plain text
chat_history = SYSTEM_PROMPT + "\n"

# First question
user_input = "What is Machine Learning?"
chat_history += f"\nUser: {user_input}\nAI:"

response = client.models.generate_content(
    model="gemini-1.5-flash",
    contents=chat_history
)

ai_reply = response.text
chat_history += ai_reply

print("AI:", ai_reply)

# Chat loop
while True:
    user_input = input("\nYou: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Chat ended.")
        break

    chat_history += f"\nUser: {user_input}\nAI:"

    response = client.models.generate_content(
        model="gemini-1.5-flash",
        contents=chat_history
    )

    ai_reply = response.text
    chat_history += ai_reply

    print("\nAI:", ai_reply)

pip install -q -U google-genai

from google import genai
from google.genai import types
from google.colab import userdata

# 1. Setup the Client using your Colab Secret
api_key = userdata.get('Gemiini_API_KEY')
client = genai.Client(api_key=api_key)

# 2. Define the Personality (System Instruction)
SYSTEM_PROMPT = """
You are an AI tutor for freshers.
Explain concepts step-by-step.
Use simple language.
Give real-world examples.
If needed, give a short code example.
Ask one follow-up question.
"""

# 3. Create the Chat Session with the correct Config
chat = client.chats.create(
    model="gemini-2.5-flash",
    config=types.GenerateContentConfig(
        system_instruction=SYSTEM_PROMPT
    )
)

print("🎓 Gemini Tutor Chat Started! (Type 'exit' to stop)\n")

# 4. The Conversation Loop
while True:
    user_input = input("You: ")

    if user_input.lower() in ["exit", "quit", "stop"]:
        print("Goodbye! Happy learning!")
        break

    # Send the message and get the response
    response = chat.send_message(user_input)

    print(f"\nAI: {response.text}\n")
    print("-" * 30)

